### ISSUE TITLE
What is your cuda version?

### ISSUE THREAD

**Issue by Jucjiaswiss** [ruinmessi/ASFF#81]
I got this error when run demo.py,
import DCN
ImportError: libcudart.so.10.1: cannot open shared object file: No such file or directory
I installed cuda-10.0, and install pytorch with command conda install pytorch=1.3.1 torchvision cudatoolkit=10.0 -c pytorch, anyone know the reason?

**Comment by Jucjiaswiss** [comment]
Problem solved. I removed the previous env and start a new one by reinstall pytorch. `conda install pytorch=1.3.1 torchvision cudatoolkit=10.0 -c pytorch` same command here but it works this time.
